name: build artifacts
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: "checking out"
        uses: actions/checkout@v3
      - name: "setting up npm"
        uses: actions/setup-node@v3
        with:
            node-version: '20.x'
      - name: "setting up Java"
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11.x'
      ############
      # CACHING
      ##########
      - name: "cache node modules"
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: "cache maven dependencies"
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: mapstore-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            mapstore-${{ runner.os }}-maven-
      ############
      # Build
      ##########
      - run : "npm install"
      - run: "npm run fe:build"
      - run: "npm run jsdoc:build"
      - run: "mvn clean install -Dmapstore2.version=$GITHUB_REF_NAME -Pprintingbundle"
      ############
      # Publish
      ##########
      - name: "Login to Docker Hub"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Build Docker image"
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mapstore2:${{ github.sha }} .

      - name: "Push Docker image to Docker Hub"
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mapstore2:${{ github.sha }}

      - uses: actions/upload-artifact@v3.1.0
        with:
            name: MapStore-Artifacts${{ github.sha }}
            path: |
                product/target/mapstore.war
                printing/target/mapstore-printing.zip
